export const COMPETITION_TEAM_LIST_REQUEST = "COMPETITION_TEAM_LIST_REQUEST";
export const COMPETITION_TEAM_LIST_SUCCESS = "COMPETITION_TEAM_LIST_SUCCESS";
export const COMPETITION_TEAM_LIST_FAIL = "COMPETITION_TEAM_LIST_FAIL";
export const COMPETITION_TEAM_LIST_RESET = "COMPETITION_TEAM_LIST_RESET";

export const COMPETITION_TEAM_DELETE_REQUEST =
  "COMPETITION_TEAM_DELETE_REQUEST";
export const COMPETITION_TEAM_DELETE_SUCCESS =
  "COMPETITION_TEAM_DELETE_SUCCESS";
export const COMPETITION_TEAM_DELETE_FAIL = "COMPETITION_TEAM_DELETE_FAIL";

export const COMPETITION_TEAM_DETAILS_REQUEST =
  "COMPETITION_TEAM_DETAILS_REQUEST";
export const COMPETITION_TEAM_DETAILS_SUCCESS =
  "COMPETITION_TEAM_DETAILS_SUCCESS";
export const COMPETITION_TEAM_DETAILS_FAIL = "COMPETITION_TEAM_DETAILS_FAIL";

export const COMPETITION_TEAM_CREATE_REQUEST =
  "COMPETITION_TEAM_CREATE_REQUEST";
export const COMPETITION_TEAM_CREATE_SUCCESS =
  "COMPETITION_TEAM_CREATE_SUCCESS";
export const COMPETITION_TEAM_CREATE_FAIL = "COMPETITION_TEAM_CREATE_FAIL";
export const COMPETITION_TEAM_CREATE_RESET = "COMPETITION_TEAM_CREATE_RESET";

export const COMPETITION_TEAM_UPDATE_REQUEST =
  "COMPETITION_TEAM_UPDATE_REQUEST";
export const COMPETITION_TEAM_UPDATE_SUCCESS =
  "COMPETITION_TEAM_UPDATE_SUCCESS";
export const COMPETITION_TEAM_UPDATE_FAIL = "COMPETITION_TEAM_UPDATE_FAIL";
export const COMPETITION_TEAM_UPDATE_RESET = "COMPETITION_TEAM_UPDATE_RESET";
