export const COMPETITION_LIST_REQUEST = "COMPETITION_LIST_REQUEST";
export const COMPETITION_LIST_SUCCESS = "COMPETITION_LIST_SUCCESS";
export const COMPETITION_LIST_FAIL = "COMPETITION_LIST_FAIL";
export const COMPETITION_LIST_RESET = "COMPETITION_LIST_RESET";

export const COMPETITION_DELETE_REQUEST = "COMPETITION_DELETE_REQUEST";
export const COMPETITION_DELETE_SUCCESS = "COMPETITION_DELETE_SUCCESS";
export const COMPETITION_DELETE_FAIL = "COMPETITION_DELETE_FAIL";
