export const COMPETITION_LIST_REQUEST = "COMPETITION_LIST_REQUEST";
export const COMPETITION_LIST_SUCCESS = "COMPETITION_LIST_SUCCESS";
export const COMPETITION_LIST_FAIL = "COMPETITION_LIST_FAIL";
export const COMPETITION_LIST_RESET = "COMPETITION_LIST_RESET";

export const COMPETITION_DELETE_REQUEST = "COMPETITION_DELETE_REQUEST";
export const COMPETITION_DELETE_SUCCESS = "COMPETITION_DELETE_SUCCESS";
export const COMPETITION_DELETE_FAIL = "COMPETITION_DELETE_FAIL";

export const COMPETITION_DETAILS_REQUEST = "COMPETITION_DETAILS_REQUEST";
export const COMPETITION_DETAILS_SUCCESS = "COMPETITION_DETAILS_SUCCESS";
export const COMPETITION_DETAILS_FAIL = "COMPETITION_DETAILS_FAIL";

export const COMPETITION_CREATE_REQUEST = "COMPETITION_CREATE_REQUEST";
export const COMPETITION_CREATE_SUCCESS = "COMPETITION_CREATE_SUCCESS";
export const COMPETITION_CREATE_FAIL = "COMPETITION_CREATE_FAIL";
export const COMPETITION_CREATE_RESET = "COMPETITION_CREATE_RESET";
